args <- commandArgs(trailingOnly = T)

#print(args[1])

x <- read.table(args[2])

#attach(x)
xm <- mean(x$V2)
xs <- sd(x$V2)
qnorm(0.005, mean = xm, sd = xs)
qnorm(0.010, mean = xm, sd = xs)
qnorm(0.015, mean = xm, sd = xs)
qnorm(0.020, mean = xm, sd = xs)
qnorm(0.025, mean = xm, sd = xs)
qnorm(0.250, mean = xm, sd = xs)
qnorm(0.750, mean = xm, sd = xs)
qnorm(0.975, mean = xm, sd = xs)
qnorm(0.980, mean = xm, sd = xs)
qnorm(0.985, mean = xm, sd = xs)
qnorm(0.990, mean = xm, sd = xs)
qnorm(0.995, mean = xm, sd = xs)

y <- read.table(args[1])
#attach(y)
ym <- mean(y$V6)
ys <- sd(y$V6)
#qnorm(0.025, mean = ym, sd = ys)
#qnorm(0.900, mean = ym, sd = ys)
#qnorm(0.950, mean = ym, sd = ys)